const AccountActionTypes = {
    SET_ACCOUNT: 'SET_ACCOUNT',
    CREATE_ACCOUNT: 'CREATE_ACCOUNT',
    ADD_TRANSACTION: 'ADD TRANSACTION',
    ADD_BUDGET: 'ADD_BUDGET',
    EDIT_BUDGET: 'EDIT_BUDGET',
    EDIT_BALANCE: 'EDIT_BALANCE',
    EDIT_INCOME: 'EDIT_INCOME',
    EDIT_NAME: 'EDIT_NAME',
}

export default AccountActionTypes